openapi: 3.0.0
info:
  description: ""
  version: "1.0.0"
  title: "issueTracker"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pyu17@fudan.edu.cn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
- url: http://10.141.221.85:8000
  description: 接口测试地址


tags:
- name: "clone 接口"


paths:
  /clonemeasure/repository:
    get:
      tags:
      - "clone 接口"
      summary: "获取克隆度量数据"
      operationId: "getMeasureCloneData"
      parameters:
      - in: "query"
        name: "repo_id"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "commit_id"
        required: true
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RepoCloneMeasureDataResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/RepoCloneMeasureDataResponse'
        '401':
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RepoCloneMeasureDataResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/RepoCloneMeasureDataResponse'

  /clonemeasure/repositoryratio:
    get:
      tags:
      - "clone 接口"
      summary: "获取克隆比率"
      operationId: "getMeasureCloneRatio"
      parameters:
      - in: "query"
        name: "repo_id"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "commit_id"
        required: true
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RepoCloneRatioResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/RepoCloneRatioResponse'
        '401':
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RepoCloneRatioResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/RepoCloneRatioResponse'

  /clonemeasure/repo-monthly:
    get:
      tags:
      - "clone 接口"
      summary: "按月统计度量信息"
      operationId: "getMeasureCloneMonthly"
      parameters:
      - in: "query"
        name: "repo_id"
        required: true
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MonthCloneMeasureResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/MonthCloneMeasureResponse'
        '401':
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MonthCloneMeasureResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/MonthCloneMeasureResponse'


components:
  schemas:
    RepoCloneMeasureData:
      type: "object"
      properties:
        repo_id:
          type: "string"
        commit_id:
          type: "string"
        clone_line:
          type: "integer"
        total_line:
          type: "integer"

    RepoCloneMeasureDataResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          $ref: '#/components/schemas/RepoCloneMeasureData'

    RepoCloneRatio:
      type: "object"
      properties:
        repo_id:
          type: "string"
        commit_id:
          type: "string"
        clone_ratio:
          type: "number"

    RepoCloneRatioResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          $ref: '#/components/schemas/RepoCloneRatio'


    MonthCloneMeasureResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          $ref: '#/components/schemas/RepoCloneInfoMonthlyList'

    RepoCloneInfoMonthly:
      type: "object"
      properties:
        date:
          type: "string"
        repo_id:
          type: "string"
        commit_id:
          type: "string"
        total_line:
          type: "integer"
        clone_line:
          type: "integer"
        clone_ratio:
          type: "number"

    RepoCloneInfoMonthlyList:
      type: "array"
      items:
        $ref: '#/components/schemas/RepoCloneInfoMonthly'






















