openapi: 3.0.0
info:
  description: ""
  version: "1.0.0"
  title: "issueTracker"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pyu17@fudan.edu.cn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
- url: http://10.141.221.85:8000
  description: 接口测试地址


tags:
- name: "event 接口"


paths:
  /event:
    post:
      tags:
      - "event 接口"
      summary: "添加事件"
      description: ""
      operationId: "addEvents"
      requestBody:
        description: "项目信息"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventList'
          application/xml:
            schema:
              $ref: '#/components/schemas/EventList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EventList'
      parameters:
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EventResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
        '401':
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EventResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'

  /event/has-new:
    get:
      tags:
      - "event 接口"
      summary: "判断是否有新的事件"
      operationId: "eventHasNew"
      parameters:
      - in: "query"
        name: "category"
        required: true
        schema:
          type: "string"
          default: "bug"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                type: "object"
                properties:
                  hasNew:
                    type: "boolean"
            application/json:
              schema:
                type: "object"
                properties:
                  hasNew:
                    type: "boolean"
        400:
          description: "failed"
          content:
            text/plain:
              schema:
                type: "object"
                properties:
                  hasNew:
                    type: "boolean"
            application/json:
              schema:
                type: "object"
                properties:
                  hasNew:
                    type: "boolean"

  /event/current-events:
    get:
      tags:
      - "event 接口"
      summary: "获取event列表"
      operationId: "getCurrentEvents"
      parameters:
      - in: "query"
        name: "category"
        required: true
        schema:
          type: "string"
          default: "bug"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetEventList'
            application/json:
              schema:
                $ref: '#/components/schemas/GetEventList'
        '401':
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetEventList'
            application/json:
              schema:
                $ref: '#/components/schemas/GetEventList'


components:
  schemas:
    Event:
      type: "object"
      properties:
        id:
          type: "string"
        category:
          type: "string"
        eventType:
          type: "string"
          enum: ["add a bug","eliminate a bug","add a clone class","remove a clone class","add a clone instance","remove a clone instance"]
        targetType:
          type: "string"
        targetId:
          type: "string"
        targetDisplayId:
          type: "string"
        targetCommitter:
          type: "string"
        repoId:
          type: "string"
        commitTime:
          type: "string"
          format: date

    EventList:
      type: "array"
      items:
        $ref: '#/components/schemas/Event'

    EventResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          type: "object"
          description: "返回的结果"

    GetEventList:
      type: "object"
      properties:
        newBug:
          $ref: '#/components/schemas/EventList'
        eliminateBug:
          $ref: '#/components/schemas/EventList'
        newCloneClass:
          $ref: '#/components/schemas/EventList'
        removeCloneClass:
          $ref: '#/components/schemas/EventList'
        newCloneInstance:
          $ref: '#/components/schemas/EventList'
        removeCloneInstance:
          $ref: '#/components/schemas/EventList'
























