openapi: 3.0.0
info:
  description: ""
  version: "1.0.0"
  title: "issueTracker"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pyu17@fudan.edu.cn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
- url: http://10.141.221.85:8000
  description: 接口测试地址


tags:
- name: "项目度量接口"
- name: "开发者度量接口"


paths:
  /measure/repository:
    get:
      tags:
        - "项目度量接口"
      summary: "获取一段时间内最新的项目度量列表"
      description: "根据时间粒度，获取每天或者每周最新的项目度量信息。"
      operationId: "getMeasureDataByRepoId"
      parameters:
        - in: "query"
          name: "repo_id"
          description: "repo的唯一ID"
          required: true
          schema:
            type: "string"
            example: "aa41c6ae-6fd0-11e9-b723-0f92b2ad63bf"
        - in: "query"
          name: "granularity"
          description: "时间粒度 "
          required: true
          schema:
            type: "string"
            enum: ["day","week","month"]
        - in: "query"
          name: "since"
          description: "从什么时候开始统计"
          required: true
          schema:
            type: "string"
            example: "2019-06-08"
        - in: "query"
          name: "until"
          description: "统计到什么时候结束"
          required: true
          schema:
            type: "string"
            example: "2019-06-09"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RepoMeasureResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/RepoMeasureResponse'
        400:
          description: "failed"

  /measure/repository/commit:
    get:
      tags:
        - "项目度量接口"
      summary: "获取一个项目在某个特定commit快照下代码行数的变化"
      description: "根据commit，获取代码行数的变化。"
      operationId: "getCodeChangesByCommit"
      parameters:
        - in: "query"
          name: "repo_id"
          description: "repo的唯一ID"
          required: true
          schema:
            type: "string"
            example: "4e21a81e-1efb-11ea-9fbe-11bdb9e75ae6"
        - in: "query"
          name: "commit_id"
          description: "commit的唯一ID"
          required: true
          schema:
            type: "string"
            example: "2deb75b97f8947bed0594d2c4b668d6d57a7a11b"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CodeChangesResponseBean'
            application/json:
              schema:
                $ref: '#/components/schemas/CodeChangesResponseBean'
        400:
          description: "failed"

  /measure/repository/duration:
    get:
      tags:
        - "项目度量接口"
      summary: "获取一个repo在一段时间内的某个开发者的commit信息"
      description: "获取一个repo在一段时间内的某个开发者的commit信息，如果不指定开发者参数，则返回所有开发者commit信息"
      operationId: "getCommitBaseInformationByDuration"
      parameters:
        - in: "query"
          name: "repo_id"
          description: "repo的唯一ID"
          required: true
          schema:
            type: "string"
            example: "4e21a81e-1efb-11ea-9fbe-11bdb9e75ae6"
        - in: "query"
          name: "since"
          description: "从什么时候开始统计"
          required: true
          schema:
            type: "string"
            example: "2019-11-11"
        - in: "query"
          name: "until"
          description: "统计到什么时候结束"
          required: true
          schema:
            type: "string"
            example: "2019-12-12"
        - in: "query"
          name: "developer_name"
          description: "开发者姓名"
          required: false
          schema:
            type: "string"
            example: "jstylejf"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CommitInfoDurationResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/CommitInfoDurationResponse'
        400:
          description: "failed"

  /measure/repository/commitBaseInfo-granularity:
    get:
      tags:
        - "项目度量接口"
      summary: "获取工作量数据"
      description: "按照不同时间段（since、until），不同聚合粒度（granularity：天/周/月），不同开发者（developerName），获取工作量数据"
      operationId: "getCommitBaseInfoGranularity"
      parameters:
        - in: "query"
          name: "repo_id"
          description: "repo的唯一ID"
          required: true
          schema:
            type: "string"
            example: "4e21a81e-1efb-11ea-9fbe-11bdb9e75ae6"
        - in: "query"
          name: "since"
          description: "从什么时候开始统计"
          required: false
          schema:
            type: "string"
            example: "2019-11-11"
        - in: "query"
          name: "until"
          description: "统计到什么时候结束"
          required: false
          schema:
            type: "string"
            example: "2019-12-12"
        - in: "query"
          name: "developer_name"
          description: "开发者姓名"
          required: false
          schema:
            type: "string"
            example: "jstylejf"
        - in: "query"
          name: "granularity"
          description: "时间聚合粒度"
          required: false
          schema:
            type: "string"
            enum: ["day","week","month"]
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CommitInfoGranularityResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/CommitInfoGranularityResponse'
        400:
          description: "failed"





components:
  schemas:
#    --------------------------------以下是接口/measure/repository:所需信息---------------------------
    RepoMeasureResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          type: "array"
          items:
            $ref: '#/components/schemas/RepoMeasure'

    RepoMeasure:
      type: "object"
      properties:
        uuid:
          type: "string"
          description: "repo measure表的唯一ID"
        files:
          type: "integer"
          description: "项目文件数"
        ncss:
          type: "integer"
          description: "有效代码行"
        classes:
          type: "integer"
          description: "项目类的数量"
        functions:
          type: "integer"
          description: "项目方法数"
        ccn:
          type: "number"
          format: "double"
          description: "圈复杂度"
        java_docs:
          type: "integer"
          description: "java doc 文档数"
        java_doc_lines:
          type: "integer"
          description: "java doc 注释行数"
        single_comment_lines:
          type: "integer"
          description: "单行注释行数"
        multi_comment_lines:
          type: "integer"
          description: "多行注释行数"
        commit_id:
          type: "string"
          description: "commit 的sh值"
        commit_time:
          type: "string"
          description: "commit提交时间"
        repo_id:
          type: "string"
          description: "repo 的唯一id"
        developer_name:
          type: "string"
          description: "开发者姓名"
        developer_email:
          type: "string"
          description: "开发者邮箱"
        add_lines:
          type: "integer"
          description: "增加行数"
        del_lines:
          type: "string"
          description: "删除行数"

    #    --------------------------------以下是接口/measure/repository/commit:所需信息---------------------------
    Developer:
      type: "object"
      properties:
        name:
          type: "string"
        email:
          type: "string"

    CommitBase:
      type: "object"
      properties:
        authors:
          type: "array"
          items:
            $ref: '#/components/schemas/Developer'
        addLines:
          type: "integer"
        delLines:
          type: "integer"

    CodeChangesResponseBean:
      type: "object"
      properties:
        code:
          type: "integer"
        msg:
          type: "string"
        data:
          $ref: '#/components/schemas/CommitBase'

  #    --------------------------------以下是接口/measure/repository/duration:所需信息---------------------------
    CommitInfoDurationResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          type: "object"
          items:
            $ref: '#/components/schemas/CommitInfoDuration'

    CommitInfoDuration:
      type: "object"
      properties:
        commitInfoList:
          type: "array"
          items:
            $ref: '#/components/schemas/CommitInfoList'
        sumAddLines:
          type: "integer"
        sumDelLines:
          type: "integer"
        sumCommitCounts:
          type: "integer"

    CommitInfoList:
      type: "object"
      properties:
        author:
          type: "string"
        email:
          type: "string"
        commit_counts:
          type: "integer"
        add:
          type: "integer"
        del:
          type: "integer"

  #    --------------------------------以下是接口/measure/repository/commitBaseInfo-granularity:所需信息---------------------------
    CommitInfoGranularityResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          type: "array"
          items:
            $ref: '#/components/schemas/CommitInfoGranularity'

    CommitInfoGranularity:
      type: "object"
      properties:
        date:
          type: "string"
          example: "2019-10-10"
        commitBaseInfoDuration:
          type: "array"
          items:
            $ref: '#/components/schemas/CommitInfoDuration'








