openapi: 3.0.0
info:
  title: "代码大数据平台API文档"
  description: ""
  version: 0.1.0

servers:
- url: http://10.141.221.85:5001
  description: 周振涛
- url: http://10.141.221.84:8102
  description: "/repository"
- url: http://10.141.221.85:8102
  description: "others"

tags:
- name: "repository-service"
- name: "commit-service"
- name: "code-service"


paths:
  /repository:
    post:
      tags:
      - "repository-service"
      operationId: "get_repo_info"
      summary: "代码库仓库查询接口"
      description: "对给定query条件和字段返回查询结果"
      requestBody:
        description: "查询条件"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/query_arg"
      responses:
        200:
          $ref: "#/components/responses/repository_response_200"
        500:
          $ref: "#/components/responses/FailedOrError"

  /commit:
    get:
      tags:
      - "commit-service"
      operationId: "get_commit"
      summary: "查询commit"
      description: "给定repo_id和page参数，返回对应的commit列表"
      parameters:
      - name: "repo_id"
        in: "query"
        description: "repository的uuid"
        required: true
        schema:
          type: "string"
      - name: "page"
        in: "query"
        description: "分页参数"
        required: false
        schema:
          type: "integer"
          format: int32
          default: 1
      - name: "per_page"
        in: "query"
        description: "每页偏移量"
        required: false
        schema:
          type: "integer"
          format: int32
          default: 50
      - name: "is_whole"
        in: "query"
        description: "如果为真返回该repo的所有commit"
        required: false
        schema:
          type: "boolean"
          example: true
          default: false
      responses:
        200:
          $ref: "#/components/responses/commit_response_200"
        500:
          $ref: "#/components/responses/FailedOrError"

  /commit/{commit_id}:
    get:
      tags:
      - "commit"
      operationId: "get_one_commit"
      summary: "查询一条commit的信息"
      description: "给定commit sha值，返回该条commit的信息"
      parameters:
      - name: "commit_id"
        in: "path"
        description: "commit的sha值"
        required: true
        schema:
          type: "string"
      responses:
        200:
          $ref: "#/components/responses/commit_response_200"
        500:
          $ref: "#/components/responses/FailedOrError"

  /commit/developer-lists-by-commits:
    post:
      tags:
      - "commit"
      operationId: "get_developer_email_by_commit"
      requestBody:
        description: "由commit sha值得到开发者的信息（现在只有邮箱）"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/commit_id_list"
      responses:
        200:
          $ref: "#/components/responses/commit_developer_list_response_200"
        500:
          $ref: "#/components/responses/FailedOrError"

  /commit/commit-time:
    get:
      tags:
      - "commit"
      operationId: "commit_time"
      summary: "查询一条commit的时间"
      description: "给定commit sha值，返回该条commit的提交时间"
      parameters:
      - name: "commit_id"
        in: "query"
        description: "commit的sha值"
        required: true
        schema:
          type: "string"
      responses:
        200:
          $ref: "#/components/responses/commit_time_response_200"
        500:
          $ref: "#/components/responses/FailedOrError"

  /code-service:
    get:
      tags:
      - "code-service"
      summary: "申请访问指定commit对应的代码库"
      operationId: "get_root_path"
      description: "对给定commit_id和repo_id返回代码库的根路径"
      parameters:
      - name: "repo_id"
        in: "query"
        description: "repository的uuid"
        required: true
        schema:
          type: "string"
      - name: "commit_id"
        in: "query"
        description: "commit的sha值"
        required: true
        schema:
          type: "string"
      responses:
        200:
          $ref: "#/components/responses/code_service_repsonse_200"
        500:
          $ref: "#/components/responses/FailedOrError"

  /code-service/free:
    get:
      tags:
      - "code-service"
      operationId: "free_resource"
      summary: "与code-service成对使用，用来释放代码库的占用权限"
      description: "指定repository的根目录和repo_id，释放其占用权限"
      parameters:
      - name: "repo_id"
        in: "query"
        description: "repository的uuid"
        required: true
        schema:
          type: "string"
      - name: "path"
        in: "query"
        description: "所占用repository的根目录"
        required: true
        schema:
          type: "string"
      responses:
        200:
          $ref: "#/components/responses/code_service_free_repsonse_200"
        500:
          $ref: "#/components/responses/FailedOrError"

  /code-service/release-generator:
    post:
      tags:
      - "code-service"
      operationId: "release_generator"
      summary: "生成release zip包"
      description: "对指定的repo_list生成其release的zip包"

      requestBody:
        description: "指定的repo_list的根路径列表"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/release_generator_arg"
      responses:
        200:
          $ref: "#/components/responses/release_generator_repsonse_200"
        500:
          $ref: "#/components/responses/FailedOrError"

components:
  schemas:
    query_arg:
      required:
      - query
      type: object
      properties:
        query:
          type: "string"
          description: "sql语句 query条件"
        page:
          type: "integer"
          format: int32
        per_page:
          type: "integer"
          format: int32
        field_list:
          type: "array"
          items:
            type: "string"
      example:
        query: "stars_count > 50 and pushed_at > '2010-01-01 00:00:00'"
        page: 1
        per_page: 2

    release_generator_arg:
      type: object
      properties:
        repo_list:
          type: "array"
          items:
            type: "string"
          description: "repo的uuid list"

    commit_id_list:
      type: "array"
      items:
        type: "string"

    repository_response:
      type: object
      properties:
        data:
          type: object
          properties:
            uuid:
              type: "string"
              description: "repo的uuid"
            local_addr:
              type: "string"
              description: "repo的本地存储地址"
            is_priviate:
              type: "boolean"
              description: "repo是否为私有库"
        count:
          type: "integer"
          format: int64
          description: "查询结果个数"
      example:
        count: 9157
        data:
        - created_at: "2008-07-26 17:22:13"
          id: 8
          local_addr: "/home/fdse/data/repo/github/rictic/code_swarm"
          repos_name: "code_swarm"
          stars_count: 336
          updated_at: "2019-04-12 18:27:47"
          uuid: "46eeed7c-c6dd-4aeb-8c57-490b1d750d0e"

        - created_at: "2008-03-01 05:22:38"
          id: 33
          local_addr: "/home/fdse/data/repo/github/dustin/java-memcached-client"
          repos_name: "java-memcached-client"
          stars_count: 467
          updated_at: "2019-04-06 03:05:48"
          uuid: "f83e5862-7816-4271-88a9-c2e842edc8cc"

    commit_response:
      type: object
      properties:
        data:
          type: object
          properties:
            uuid:
              type: "string"
              description: "commit的uuid"
            commit_id:
              type: "string"
              description: "commit的sha值"
            message:
              type: "string"
            developer:
              type: "string"
              description: "提交者邮箱"
            commit_time:
              type: "string"
              format: date
            repo_id:
              type: "string"
              description: "该commit所属repo的uuid"

    commit_developer_list_response:
      type: object
      properties:
        data:
          type: object
          properties:
            commit_id:
              type: object
              properties:
                developer_email:
                  type: "string"
        status:
          type: "string"
      example:
        data:
        - ada884e52ceb8713327e4a36a7a147c0e783d099: "k8s-ci-robot@users.noreply.github.com"
        - e0cd19bc52dc4763f2059944b409c998c0e60af5: "tatu.saloranta@iki.fi"
        status:
          "Successful"

    commit_time_response:
      type: object
      properties:
        data:
          type: object
          properties:
            commit_time:
              type: "string"
              format: date

    code_service_repsonse:
      type: object
      properties:
        data:
          type: object
          properties:
            status:
              type: "string"
            content:
              type: "string"
      example:
        data:
          status: "Successful"
          content: "/home/fdse/user/iussueTracker/repo/github/zxing/zxing-master"

    code_service_free_repsonse:
      type: object
      properties:
        data:
          type: object
          properties:
            status:
              type: "string"

    release_generator_repsonse:
      type: object
      properties:
        data:
          type: object
          properties:
            status:
              type: "string"

    error_response:
      type: object
      properties:
        message:
          type: "string"
          description: "失败原因"



  responses:
    FailedOrError:
      description: "查询失败或异常"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error_response'

    repository_response_200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/repository_response'

    commit_response_200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/commit_response'

    commit_developer_list_response_200:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/commit_developer_list_response'

    commit_time_response_200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/commit_time_response"

    code_service_repsonse_200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/code_service_repsonse"

    code_service_free_repsonse_200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/code_service_free_repsonse"

    release_generator_repsonse_200:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/release_generator_repsonse"

