openapi: 3.0.0
info:
  description: ""
  version: "1.0.0"
  title: "issueTracker"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pyu17@fudan.edu.cn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
- url: http://10.141.221.85:8000
  description: 接口测试地址


tags:
- name: "project 接口"


paths:
  /project:
    post:
      tags:
      - "project 接口"
      summary: "添加项目"
      description: "提供项目的必要信息，完成项目的下载。"
      operationId: "addProject"
      requestBody:
        description: "项目信息"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/projectInfo'
      parameters:
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AddProjectResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/AddProjectResponse'
        '401':
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AddProjectResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/AddProjectResponse'

    get:
      tags:
      - "project 接口"
      summary: "获取项目列表"
      description: "根据工具类型获取项目列表"
      operationId: "query"
      parameters:
      - in: "query"
        name: "type"
        description: "工具类型"
        required: false
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProjectList'
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectList'
        400:
          description: "failed"


  /project/filter:
    get:
      tags:
      - "project 接口"
      summary: "根据关键字获取项目列表"
      description: "根据工具类型获取项目列表"
      operationId: "keyWordQuery"
      parameters:
      - in: "query"
        name: "keyWord"
        description: "筛选关键字"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "type"
        description: "工具类型"
        required: false
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProjectList'
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectList'
        400:
          description: "failed"

  /project/name:
    get:
      tags:
      - "project 接口"
      summary: "根据repo id获取项目列表"
      description: "根据工具类型获取项目列表"
      operationId: "getProjectName"
      parameters:
      - in: "query"
        name: "repoId"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "type"
        description: "工具类型"
        required: false
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProjectSearchResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectSearchResponse'
        400:
          description: "failed"

  /project/search:
    get:
      tags:
      - "project 接口"
      summary: "根据条件获取项目列表"
      description: "根据工具类型获取项目列表"
      operationId: "getProjectByCondition"
      parameters:
      - in: "query"
        name: "name"
        required: false
        schema:
          type: "string"
      - in: "query"
        name: "category"
        description: "工具类型"
        required: false
        schema:
          type: "string"
      - in: "query"
        name: "module"
        description: "项目所属模块"
        required: false
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProjectList'
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectList'
        400:
          description: "failed"


components:
  schemas:
    projectInfo:
      type: "object"
      properties:
        url:
          type: "string"
        name:
          type: "string"
        type:
          type: "string"
        isPrivate:
          type: "boolean"
        branch:
          type: "string"
        username:
          type: "string"
        password:
          type: "string"
        module:
          type: "string"

    AddProjectResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          type: "object"

    ProjectList:
      type: "array"
      items:
        $ref: '#/components/schemas/Project'

    Project:
      type: "object"
      properties:
        uuid:
          type: "string"
        name:
          type: "string"
        language:
          type: "string"
        url:
          type: "string"
        vcs_type:
          type: "string"
        type:
          type: "string"
        account_id:
          type: "string"
        download_status:
          type: "string"
        scan_status:
          type: "string"
        add_time:
          type: "string"
        till_commit_time:
          type: "string"
        last_scan_time:
          type: "string"
        description:
          type: "string"
        repo_id:
          type: "string"
        branch:
          type: "string"
        first_auto_scan:
          type: "integer"
        module:
          type: "string"

    ProjectSearchResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          $ref: '#/components/schemas/ProjectList'



























