openapi: 3.0.0
info:
  description: ""
  version: "1.0.0"
  title: "issueTracker"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pyu17@fudan.edu.cn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

servers:
- url: http://10.141.221.85:8000
  description: 接口测试地址


tags:
- name: "scan 接口"


paths:
  /scan:
    post:
      tags:
      - "scan 接口"
      summary: "开始扫描"
      description: ""
      operationId: "scan"
      requestBody:
        description: "扫描信息"
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ScanInfo'
      parameters:
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ScanInfoResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ScanInfoResponse'
        '401':
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ScanInfoResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ScanInfoResponse'

  /scan/commits:
    get:
      tags:
      - "scan 接口"
      summary: "根据条件获取commit列表"
      operationId: "query"
      parameters:
      - in: "query"
        name: "project_id"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "page"
        required: false
        schema:
          type: "integer"
          default: 1
      - in: "query"
        name: "size"
        required: false
        schema:
          type: "integer"
          default: 10
      - in: "query"
        name: "is_whole"
        required: false
        schema:
          type: "boolean"
          default: false
      - in: "query"
        name: "category"
        required: true
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CommitListResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/CommitListResponse'
        400:
          description: "failed"

  /scan/next-scanned-commits:
    get:
      tags:
      - "scan 接口"
      summary: "获取指定commit的下一条commit"
      operationId: "getNextScannedCommit"
      parameters:
      - in: "query"
        name: "repo_id"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "category"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "commit_id"
        required: true
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'
        400:
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'

  /scan/pre-scanned-commits:
    get:
      tags:
      - "scan 接口"
      summary: "获取指定commit的上一条commit"
      operationId: "getPreScannedCommit"
      parameters:
      - in: "query"
        name: "repo_id"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "category"
        required: true
        schema:
          type: "string"
      - in: "query"
        name: "commit_id"
        required: true
        schema:
          type: "string"
      - in: "header"
        name: "token"
        description: "用户token"
        required: true
        schema:
          type: "string"
      responses:
        '200':
          description: "successful operation"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'
        400:
          description: "failed"
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnCommitsResponse'


components:
  schemas:
    ScanInfo:
      type: "object"
      properties:
        category:
          type: "string"
        projectId:
          type: "string"
        commitId:
          type: "string"


    ScanInfoResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          type: "object"

    CommitListResponse:
      type: "object"
      properties:
        totalCount:
          type: "integer"
        commitList:
          type: "array"
          items:
            type: "object"

    ReturnCommitsResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          example: 200
          description: "如果响应成功则返回200状态码，响应失败返回返回其他状态码。"
        msg:
          type: "string"
          description: "响应返回的基本消息"
        data:
          type: "string"
          description: "返回的结果"

























